/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pc;

import java.awt.Dialog;
import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Shin
 */
public class JoinPanel extends javax.swing.JPanel {

    NewJFrame nf;
    LoginPanel lp;

    /**
     * Creates new form JoinPanel
     */
    public JoinPanel() {
        initComponents();
        this.setSize(500, 500);
    }

    public JoinPanel(NewJFrame mainframe, LoginPanel lp) {
        initComponents();
        this.setSize(500, 500);
        this.nf = mainframe;
        nf.setSize(500, 700);
        this.lp = lp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        numberTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        acceptButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();

        jLabel1.setText("ID");

        jLabel2.setText("비밀번호");

        jLabel3.setText("이름");

        jLabel4.setText("학번");

        jLabel5.setText("E-mail");

        acceptButton.setText("가입");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("취소");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acceptButton)
                        .addGap(88, 88, 88)
                        .addComponent(cancelButton))
                    .addComponent(idTextField)
                    .addComponent(nameTextField)
                    .addComponent(numberTextField)
                    .addComponent(emailTextField)
                    .addComponent(PasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(numberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptButton)
                    .addComponent(cancelButton))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        if (evt.getSource() == acceptButton) {
            if (insertMember()) {
                //회원 가입에 성공하였을 경우 메인프레임의 패널을 로그인패널로 전환한다.
                System.out.println("insertMember() 호출 종료");
                nf.setSize(nf.WIDTH, nf.HEIGHT);
                nf.changePanel(lp);
            } else {
                //회원 가입에 실패하였을 경우 패널 전환을 하지 않는다
            }
        }
    }//GEN-LAST:event_acceptButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if (evt.getSource() == cancelButton) {
            nf.setSize(nf.WIDTH, nf.HEIGHT);
            nf.changePanel(lp);

        }
    }//GEN-LAST:event_cancelButtonActionPerformed
    private boolean insertMember() {

        //화면에서 사용자가 입력한 내용을 얻는다.
        Memberinfo dto = getViewData();
        DBconnector dao = new DBconnector();
        boolean ok = dao.insertMember(dto);

        if (ok) {

            JOptionPane.showMessageDialog(this, "가입이 완료되었습니다.");
            //dispose();
            return true;

        } else {

            JOptionPane.showMessageDialog(this, "가입이 정상적으로 처리되지 않았습니다.");
            return false;
        }

    }//insertMember
    private void UpdateMember() {
		
		//1. 화면의 정보를 얻는다.
		Memberinfo minfo = getViewData();		
		//2. 그정보로 DB를 수정
		DBconnector db = new DBconnector();
		boolean ok = db.updateMember(minfo);
		
		if(ok){
			JOptionPane.showMessageDialog(this, "수정되었습니다.");
                        
		}else{
			JOptionPane.showMessageDialog(this, "수정실패: 값을 확인하세요");	
		}
	}
    public Memberinfo getViewData() {

        //화면에서 사용자가 입력한 내용을 얻는다.
        Memberinfo dto = new Memberinfo();
        String id = idTextField.getText();
        String pwd = PasswordField.getText();
        String name = nameTextField.getText();
        String snumber = numberTextField.getText();
        String email = emailTextField.getText();

        //dto에 담는다.
        dto.setId(id);
        dto.setPwd(pwd);
        dto.setName(name);
        dto.setNumber(snumber);
        dto.setEmail(email);

        return dto;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField numberTextField;
    // End of variables declaration//GEN-END:variables
}
